@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ru.gelonsoft.silentaddons.client.models;
import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;