@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ru.gelonsoft.silentaddons.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;